spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
    url: jdbc:mariadb://localhost:3306/arcadedb?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
  profiles:
    active: dev
  thymeleaf:
    cache: false
    check-template: true
    encoding: UTF-8
